/*
 * File: app/view/LoginWindowViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SECURITY.view.LoginWindowViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.loginwindow',

    onSpecialkey: function(field, e, eOpts) {
        //should be handled
        /*if(e.getKey() === e.ENTER){
        this.doLogin();
        }*/
    },

    onSpecialKey1: function(field, e, eOpts) {
        //should ne handled
        /*if(e.getKey() === e.ENTER){
        this.doLogin();
        } */
    },

    onLoginClick: function(button, e, eOpts) {
        var view = this.getView(),
            form = button.up('form'),
            formWindow = button.up('window');
        var userName = form.down('textfield[name=userName]').getValue();
        var password = form.down('textfield[name=password]').getValue();
        var applicationCode = form.down('combobox').getValue();
        window.localStorage.setItem('appCode',applicationCode);
        // Success
        var successCallback = function (resp, ops) {
            // Close window


            resp = Ext.decode(resp.responseText);
            if(resp.success){
                formWindow.destroy();
                Ext.create('SECURITY.view.MyViewport');


            }else{

                Ext.Msg.alert({
                    title: 'Error',
                    msg: 'Invalid username or password',
                    buttons: Ext.Msg.OK,
                    icon: Ext.Msg.ERROR
                });
            }

        };

        // Failure
        var failureCallback = function (resp, ops) {

            // Show login failure error
            Ext.Msg.alert({
                title: 'Error',
                msg: 'Error',
                buttons: Ext.Msg.OK,
                icon: Ext.Msg.ERROR
            });
        };


        if (userName.toLowerCase() !== 'test') {
            // Login using server-side authentication service
            Ext.Ajax.request({
                url: "/DIAM_SECURITY/app/login",
                method: 'POST',
                params: {
                    userName: userName,
                    password: password,
                    applicationCode: applicationCode
                },
                success: successCallback,
                failure: failureCallback
            });
        }else{
            formWindow.destroy();
            Ext.create('SECURITY.view.MyViewport');

        }


    }

});
