/*
 * File: app/view/LoginWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SECURITY.view.LoginWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.loginwindow',

    requires: [
        'SECURITY.view.LoginWindowViewModel',
        'SECURITY.view.LoginWindowViewController',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'loginwindow',
    viewModel: {
        type: 'loginwindow'
    },
    autoShow: true,
    border: false,
    cls: 'login',
    resizable: false,
    layout: 'fit',
    closable: false,
    title: 'Login',

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    reference: 'userName',
                    fieldLabel: 'User Name',
                    name: 'userName',
                    fieldStyle: 'background:#F0F2B3',
                    listeners: {
                        specialkey: 'onSpecialkey'
                    }
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    reference: 'password',
                    fieldLabel: 'Password',
                    name: 'password',
                    fieldStyle: 'background:#F0F2B3',
                    inputType: 'password',
                    listeners: {
                        specialkey: 'onSpecialKey1'
                    }
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    reference: 'applicationCode',
                    fieldLabel: 'Application',
                    name: 'applicationCode',
                    fieldStyle: 'background:#F0F2B3',
                    displayField: 'applicationCode',
                    forceSelection: true,
                    store: 'applicationCode',
                    valueField: 'applicationCode'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Login',
                            listeners: {
                                click: 'onLoginClick'
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Cancel'
                        }
                    ]
                }
            ]
        }
    ]

});