/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SECURITY.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'SECURITY.view.MyViewportViewModel',
        'SECURITY.view.MyViewportViewController',
        'SECURITY.view.Users',
        'SECURITY.view.Roles',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    controller: 'myviewport',
    viewModel: {
        type: 'myviewport'
    },
    height: 250,
    width: 400,
    layout: 'border',

    items: [
        {
            xtype: 'container',
            region: 'center',
            id: 'container',
            itemId: 'container',
            layout: 'card',
            items: [
                {
                    xtype: 'users',
                    itemId: 'usersPanel'
                },
                {
                    xtype: 'roles',
                    itemId: 'rolesPanel'
                }
            ]
        },
        {
            xtype: 'toolbar',
            region: 'north',
            height: 37,
            items: [
                {
                    xtype: 'button',
                    text: 'Adminstration',
                    menu: {
                        xtype: 'menu',
                        width: 120,
                        items: [
                            {
                                xtype: 'menuitem',
                                text: 'Roles',
                                listeners: {
                                    click: 'onRolestemClick'
                                }
                            },
                            {
                                xtype: 'menuitem',
                                text: 'Users',
                                listeners: {
                                    click: 'onUsersItemClick'
                                }
                            }
                        ]
                    }
                }
            ]
        }
    ]

});