/*
 * File: app/view/Users.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SECURITY.view.Users', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.users',

    requires: [
        'SECURITY.view.UsersViewModel',
        'SECURITY.view.UsersViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.form.field.Display',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.FieldContainer',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Tag',
        'Ext.button.Button',
        'Ext.toolbar.Toolbar'
    ],

    controller: 'users',
    viewModel: {
        type: 'users'
    },
    height: 1000,
    shrinkWrap: 0,
    width: 1200,
    layout: 'border',
    collapsed: false,
    title: 'User Management',

    items: [
        {
            xtype: 'gridpanel',
            flex: 1,
            region: 'center',
            split: true,
            reference: 'list',
            resizable: false,
            title: '',
            forceFit: true,
            bind: {
                store: '{users}'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'id',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'userName',
                    text: 'User Name'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return value !== null ? value.length : '';
                    },
                    dataIndex: 'roles',
                    text: 'Roles'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return value === true ? 'Yes' : 'No';
                    },
                    dataIndex: 'active',
                    text: 'Active'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'firstName',
                    text: 'First Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'lastName',
                    text: 'Last Name'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'passwordLastChangedDate',
                    text: 'Password Last Changed',
                    format: 'm/j/Y'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'lastLoginDate',
                    text: 'Last Login',
                    format: 'm/j/Y'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return Ext.Date.format(value, 'm/d/Y');
                    },
                    dataIndex: 'updatedOn',
                    text: 'Updated'
                }
            ],
            listeners: {
                select: 'select'
            }
        },
        {
            xtype: 'panel',
            flex: 1,
            region: 'south',
            split: true,
            reference: 'display',
            height: 150,
            layout: 'card',
            bodyBorder: true,
            items: [
                {
                    xtype: 'panel',
                    reference: 'selectMessage',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            html: '<h1>Please select a record</h1>'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    reference: 'details',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'User Name',
                            bind: {
                                value: '{record.userName}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Combined Actions',
                            bind: {
                                value: '{record.combinedActions}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Notification Frequency Id',
                            bind: {
                                value: '{record.notificationFrequencyId}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'First Name',
                            bind: {
                                value: '{record.firstName}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Last Name',
                            bind: {
                                value: '{record.lastName}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Email',
                            bind: {
                                value: '{record.email}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Work Phone Number',
                            bind: {
                                value: '{record.workPhoneNumber}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Nice Net Number',
                            bind: {
                                value: '{record.niceNetNumber}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Must Change Password',
                            bind: {
                                value: '{record.mustChangePassword}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Active',
                            bind: {
                                value: '{record.active}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Password Last Changed Date',
                            bind: {
                                value: '{record.passwordLastChangedDate}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Last Login Date',
                            bind: {
                                value: '{record.lastLoginDate}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Sales Company Ids',
                            bind: {
                                value: '{record.salesCompanyIds}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Customer Group Ids',
                            bind: {
                                value: '{record.customerGroupIds}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Affiliate Ids',
                            bind: {
                                value: '{record.affiliateIds}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Warehouse Ids',
                            bind: {
                                value: '{record.warehouseIds}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Role Ids For Sales Company',
                            bind: {
                                value: '{record.roleIdsForSalesCompany}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Role Ids For Affiliate',
                            bind: {
                                value: '{record.roleIdsForAffiliate}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Role Ids For Warehouse',
                            bind: {
                                value: '{record.roleIdsForWarehouse}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Role Ids For Generic',
                            bind: {
                                value: '{record.roleIdsForGeneric}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Created By',
                            bind: {
                                value: '{record.createdBy}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Created By User Id',
                            bind: {
                                value: '{record.createdByUserId}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Updated By User Id',
                            bind: {
                                value: '{record.updatedByUserId}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Created On',
                            bind: {
                                value: '{record.createdOn}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Updated On',
                            bind: {
                                value: '{record.updatedOn}'
                            }
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Updated By',
                            bind: {
                                value: '{record.updatedBy}'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    reference: 'formMain',
                    layout: 'border',
                    items: [
                        {
                            xtype: 'form',
                            region: 'center',
                            reference: 'formFields',
                            scrollable: true,
                            bodyPadding: 10,
                            title: 'Edit User',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'User Info',
                                    layout: {
                                        type: 'table',
                                        columns: 3,
                                        tdAttrs: {
                                            style: 'padding: 10px;'
                                        }
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: '',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Email',
                                                    name: 'email',
                                                    allowBlank: false,
                                                    bind: {
                                                        value: '{record.email}'
                                                    }
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Work Phone Number',
                                                    name: 'workPhoneNumber',
                                                    bind: {
                                                        value: '{record.workPhoneNumber}'
                                                    }
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Nice Net Number',
                                                    name: 'niceNetNumber',
                                                    bind: {
                                                        value: '{record.niceNetNumber}'
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: '',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'First Name',
                                                    name: 'firstName',
                                                    allowBlank: false,
                                                    maxLength: 30,
                                                    minLength: 2,
                                                    bind: {
                                                        value: '{record.firstName}'
                                                    }
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Last Name',
                                                    name: 'lastName',
                                                    allowBlank: false,
                                                    maxLength: 30,
                                                    minLength: 2,
                                                    bind: {
                                                        value: '{record.lastName}'
                                                    }
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'User Name',
                                                    name: 'userName',
                                                    bind: {
                                                        value: '{record.userName}'
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            fieldLabel: '',
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    fieldLabel: 'Active',
                                                    name: 'active',
                                                    bind: {
                                                        value: '{record.active}'
                                                    }
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    width: 298,
                                                    fieldLabel: 'Notification Frequency',
                                                    name: 'notificationFrequencyId',
                                                    editable: false,
                                                    displayField: 'code',
                                                    queryMode: 'local',
                                                    valueField: 'id',
                                                    bind: {
                                                        value: '{record.notificationFrequencyId}',
                                                        store: '{NotificationFrequencyStore}'
                                                    }
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    renderer: function(value, displayField) {
                                                        return Ext.Date.format(value, 'm/d/Y');
                                                    },
                                                    fieldLabel: 'Last Login Date',
                                                    name: 'lastLoginDate',
                                                    bind: {
                                                        value: '{record.lastLoginDate}'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    reference: 'salesCompanyPanel',
                                    hidden: true,
                                    layout: 'column',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Sales Company Roles',
                                            items: [
                                                {
                                                    xtype: 'tagfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Roles'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    reference: 'salesDeptPanel',
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Roles',
                                            items: [
                                                {
                                                    xtype: 'tagfield',
                                                    fieldLabel: 'Roles',
                                                    displayField: 'name',
                                                    store: 'roles',
                                                    valueField: 'id',
                                                    bind: {
                                                        value: '{record.roles}'
                                                    }
                                                },
                                                {
                                                    xtype: 'tagfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Sales Dept\'s',
                                                    displayField: 'name',
                                                    valueField: 'id',
                                                    bind: {
                                                        value: '{record.salesDepartment}',
                                                        store: '{SalesDepartmentStore}'
                                                    },
                                                    listeners: {
                                                        beforeselect: 'onSalesDeptBeforeSelect'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    reference: 'genericRolesPanel',
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Other Roles',
                                            items: [
                                                {
                                                    xtype: 'tagfield',
                                                    anchor: '100%',
                                                    fieldLabel: 'Roles',
                                                    name: 'roleIdsForGeneric',
                                                    displayField: 'name',
                                                    valueField: 'id',
                                                    bind: {
                                                        value: '{record.roleIdsForGeneric}',
                                                        store: '{GenericRoles}'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    reference: 'additionalUserInformation',
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Additional User Information',
                                            items: [
                                                {
                                                    xtype: 'displayfield',
                                                    renderer: function(value, displayField) {
                                                        return Ext.Date.format(value, 'm/d/Y');
                                                    },
                                                    fieldLabel: 'Updated On',
                                                    name: 'updatedOn',
                                                    bind: {
                                                        value: '{record.updatedOn}'
                                                    }
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    renderer: function(value, displayField) {
                                                        return Ext.Date.format(value, 'm/d/Y');
                                                    },
                                                    fieldLabel: 'Created On',
                                                    name: 'createdOn',
                                                    bind: {
                                                        value: '{record.createdOn}'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    padding: 10,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            formBind: true,
                                            itemId: 'saveButton',
                                            margin: 5,
                                            text: 'Save',
                                            listeners: {
                                                click: 'save'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            itemId: 'cancelButton',
                                            margin: 5,
                                            text: 'Cancel',
                                            listeners: {
                                                click: 'cancelEdit'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    text: 'Add',
                    listeners: {
                        click: 'add'
                    }
                },
                {
                    xtype: 'button',
                    text: 'Edit',
                    bind: {
                        hidden: '{!record}'
                    },
                    listeners: {
                        click: 'edit'
                    }
                },
                {
                    xtype: 'button',
                    reference: 'btnDelete',
                    text: 'Remove',
                    bind: {
                        hidden: '{!record}'
                    },
                    listeners: {
                        click: 'remove'
                    }
                }
            ]
        }
    ]

});