/*
 * File: app/model/ActionsAssignedToRoleDTO.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SECURITY.model.ActionsAssignedToRoleDTO', {
    extend: 'Ext.data.Model',
    alias: 'model.actionsassignedtoroledto',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            name: 'description'
        },
        {
            type: 'int',
            name: 'actionId'
        },
        {
            type: 'string',
            name: 'code'
        },
        {
            type: 'int',
            name: 'roleId'
        },
        {
            type: 'string',
            name: 'functionality'
        },
        {
            type: 'string',
            name: 'permissionType'
        },
        {
            type: 'int',
            name: 'roleActionId'
        },
        {
            type: 'boolean',
            name: 'assigned'
        },
        {
            type: 'int',
            name: 'applicationId'
        },
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'boolean',
            name: 'canView'
        },
        {
            type: 'boolean',
            name: 'canEdit'
        },
        {
            type: 'boolean',
            name: 'canApprove'
        },
        {
            type: 'string',
            name: 'applicationCode'
        }
    ]
});