/*
 * File: app/model/Action.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SECURITY.model.Action', {
    extend: 'Ext.data.Model',
    alias: 'model.action',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],
    uses: [
        'SECURITY.model.AdjustmentStatus'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'string',
            name: 'type'
        },
        {
            name: 'description'
        },
        {
            type: 'int',
            name: 'permissionId'
        },
        {
            type: 'string',
            name: 'code'
        },
        {
            type: 'int',
            name: 'applicationId'
        }
    ],

    hasMany: {
        associatedName: 'applicableStatuses',
        model: 'SECURITY.model.AdjustmentStatus'
    }
});