/*
 * File: app/model/CustomerGroup2.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SECURITY.model.CustomerGroup2', {
    extend: 'Ext.data.Model',
    alias: 'model.customergroup2',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer',
        'Ext.data.field.Date'
    ],

    idProperty: 'customerGroupId',

    fields: [
        {
            type: 'string',
            name: 'description'
        },
        {
            type: 'int',
            name: 'customerGroupId'
        },
        {
            type: 'string',
            name: 'code2'
        },
        {
            type: 'string',
            name: 'code3'
        },
        {
            name: 'tier1Ids'
        },
        {
            name: 'code3AndDescription'
        },
        {
            type: 'int',
            name: 'updatedByUserId'
        },
        {
            type: 'date',
            name: 'modifiedOn'
        },
        {
            type: 'date',
            name: 'createdOn'
        },
        {
            type: 'int',
            name: 'createdByUserId'
        }
    ]
});