/*
 * File: app/model/Facility.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SECURITY.model.Facility', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'facilityId'
        },
        {
            name: 'description'
        },
        {
            name: 'code2'
        },
        {
            name: 'code3'
        },
        {
            name: 'code4'
        },
        {
            name: 'responsibleAffiliate'
        },
        {
            name: 'canCharge'
        },
        {
            name: 'canSeeSalesCompanyPricing'
        },
        {
            name: 'naopipFacility'
        },
        {
            defaultValue: 0,
            name: 'parentFacilityId'
        }
    ]
});