/*
 * File: app/model/Role.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SECURITY.model.Role', {
    extend: 'Ext.data.Model',
    alias: 'model.role',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Date'
    ],
    uses: [
        'SECURITY.model.Action',
        'SECURITY.model.RoleType'
    ],

    clientIdProperty: 'id',

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'string',
            name: 'groupEmail'
        },
        {
            type: 'string',
            name: 'name'
        },
        {
            name: 'createdBy'
        },
        {
            type: 'date',
            name: 'updatedOn',
            dateReadFormat: 'time',
            dateWriteFormat: 'c'
        },
        {
            name: 'updatedBy'
        },
        {
            critical: true,
            name: 'roleType',
            persist: true
        },
        {
            type: 'int',
            name: 'roleTypeId'
        },
        {
            type: 'date',
            name: 'createdOn',
            dateReadFormat: 'time',
            dateWriteFormat: 'c'
        },
        {
            type: 'int',
            name: 'applicationId'
        },
        {
            type: 'string',
            name: 'applicationCode'
        }
    ],

    hasMany: {
        associationKey: 'actions',
        model: 'SECURITY.model.Action'
    },

    hasOne: {
        associationKey: 'roleTypes',
        model: 'SECURITY.model.RoleType',
        name: 'roleTypes'
    }
});