/*
 * File: app/model/SalesCompany.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SECURITY.model.SalesCompany', {
    extend: 'Ext.data.Model',
    alias: 'model.salescompany',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer'
    ],

    fields: [
        {
            type: 'string',
            name: 'description'
        },
        {
            type: 'string',
            name: 'companyCode'
        },
        {
            type: 'string',
            name: 'companyNumber'
        },
        {
            type: 'string',
            name: 'companyAbbreviation'
        },
        {
            type: 'string',
            name: 'createUserId'
        },
        {
            type: 'int',
            name: 'updateDateTime'
        },
        {
            type: 'int',
            allowNull: true,
            name: 'salesCompanyId'
        },
        {
            name: 'createdOn'
        }
    ]
});