/*
 * File: app/model/User.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SECURITY.model.User', {
    extend: 'Ext.data.Model',
    alias: 'model.user',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Boolean',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'string',
            name: 'userName'
        },
        {
            name: 'roles'
        },
        {
            name: 'combinedActions'
        },
        {
            type: 'int',
            name: 'notificationFrequencyId'
        },
        {
            type: 'string',
            name: 'firstName'
        },
        {
            type: 'string',
            name: 'lastName'
        },
        {
            name: 'email'
        },
        {
            type: 'string',
            name: 'workPhoneNumber'
        },
        {
            type: 'string',
            name: 'niceNetNumber'
        },
        {
            type: 'boolean',
            name: 'mustChangePassword'
        },
        {
            type: 'boolean',
            name: 'active'
        },
        {
            type: 'date',
            name: 'passwordLastChangedDate',
            dateReadFormat: 'time',
            dateWriteFormat: 'c'
        },
        {
            type: 'date',
            name: 'lastLoginDate',
            dateReadFormat: 'time',
            dateWriteFormat: 'c'
        },
        {
            name: 'salesCompanyIds'
        },
        {
            name: 'customerGroupIds'
        },
        {
            name: 'affiliateIds'
        },
        {
            name: 'warehouseIds'
        },
        {
            name: 'roleIdsForSalesCompany'
        },
        {
            name: 'roleIdsForAffiliate'
        },
        {
            name: 'roleIdsForWarehouse'
        },
        {
            name: 'roleIdsForGeneric'
        },
        {
            name: 'createdBy'
        },
        {
            type: 'int',
            name: 'createdByUserId'
        },
        {
            type: 'int',
            name: 'updatedByUserId'
        },
        {
            type: 'date',
            name: 'createdOn',
            dateReadFormat: 'time',
            dateWriteFormat: 'c'
        },
        {
            type: 'date',
            name: 'updatedOn',
            dateReadFormat: 'time',
            dateWriteFormat: 'c'
        },
        {
            name: 'updatedBy'
        },
        {
            name: 'salesDepartment'
        },
        {
            type: 'int',
            name: 'applicationId'
        },
        {
            type: 'string',
            name: 'applicationCode'
        }
    ]
});